export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
export const LOGOUT = "LOGOUT"

export const REQUEST_USERS = "REQUEST_USERS"

export const FILE_GRIEVANCE = "FILE_GRIEVANCE"

export const RESET_FORM = "RESET_FORM"

export const ADD_COMMENT = "ADD_COMMENT"
